spring.application.name=achievements

spring.kafka.bootstrap-servers=broker:29092
spring.kafka.consumer.group-id=my-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
# Tell Kafka to expect JSON
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell Spring exactly which Java class to turn that JSON into
spring.kafka.consumer.properties.spring.json.value.default.type=mason.beale.achievements.events.PlayerActionEvent

# Trust the incoming package 
spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.type.mapping=playerActionEvent:mason.beale.achievements.events.PlayerActionEvent
